#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/WeatherPlugin
rm -rf /usr/lib/enigma2/python/Components/Converter/MSNWeather.py*
rm -rf /usr/lib/enigma2/python/Components/Renderer/MSNWeatherPixmap.py*
rm -rf /usr/lib/enigma2/python/Components/WeatherMSN.py*
rm -rf /usr/lib/enigma2/python/Components/Sources/MSNWeather.py*
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/WeatherPlugin
rm -rf /usr/lib/enigma2/python/Plugins/SkinComponents/WeatherComponent/README.*
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/WeatherComponentHandler/*.*
rm -rf /usr/share/enigma2/Pd1loi-HD-night
echo
echo      Rebooting now....
sleep 2
init 4 && sleep 3 && init 3
