#!/bin/sh
echo "                                                           "
echo "      The Skin Pd1loi-HD-night is now being removed...     "
echo "                                                           "
